name: Download and Process OMIE Prices

on:
  schedule:
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'
    - cron: '0 23 * * *'  # ⏰ Final fallback — run `append_new_day.py`
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas duckdb requests pyarrow

      - name: Download OMIE data
        run: python download_tomorrow.py

      - name: Append new day to database
        run: python append_new_day.py

      - name: Commit and push processed files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git pull --rebase origin main  # 👈 Pull first with rebase to avoid conflicts
          
          git add processed/*.parquet processed/*.csv processed/*.duckdb || echo "No new files to add"
          git commit -m "📊 Update processed data files" || echo "No changes to commit"
          git push || echo "Nothing to push"


          

