name: Download and Process OMIE Prices

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6:00 UTC (8:00 CEST approx)
  workflow_dispatch:      # Allow manual runs

jobs:
  download-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas duckdb

      - name: Run download script
        run: python download_tomorrow.py

      - name: Append to database
        run: python append_new_day.py

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "📊 Update OMIE database with new prices" || echo "No changes to commit"
          git push
