name: Download and Process OMIE Prices

on:
  schedule:
    - cron: '0 18 * * *'   # ⏰ Main run after OMIE releases
    - cron: '0 20 * * *'   # ⏰ Redundant run (failsafe)
    - cron: '0 22 * * *'   # ⏰ Backup
    - cron: '0 23 * * *'   # ⏰ Final fallback
  workflow_dispatch:       # ✅ Allow manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas duckdb requests pyarrow

      - name: Download OMIE data
        run: python download_tomorrow.py

      - name: Append new day to database
        run: python append_new_day.py

      - name: Build database files
        run: python build_master_database.py

      - name: Push processed files to GitHub 🚀
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git reset --hard HEAD                 # 🧼 Clean up local changes
          git pull --rebase origin main || true
          git add processed/*
          git commit -m "📊 Update processed files" || echo "No changes to commit"
          git push || echo "Nothing to push"
